import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Navigation } from '@/components/Navigation/Navigation'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
const type = "Home";

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navigation />
        <h1 className={styles.title}>This is a {type} page</h1>
      </main>
    </>
  )
}
